# Generated by Django 4.0.1 on 2022-01-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contatos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='mostrar',
            field=models.BooleanField(default=True),
        ),
    ]
